language: rust
rust:
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_install:
  - sudo apt-get install libvips*
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
deploy:
  provider: releases
  api_key:
    secure: 63ccede76c573efa918ad7c6103d804d97c5af89
  file: "./target/debug/test"
  skip_cleanup: true
  on:
    tags: true