language: rust
rust:
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_install:
  - sudo apt-get install libvips*
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "./target/debug/test"
  skip_cleanup: true
  on:
    branch: master
    tags: true