language: rust
rust:
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_install:
  - sudo apt-get install libvips*
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
deploy:
  provider: releases
  api_key:
    secure: "54d38a51f2d466512b66a7fb4505d0410ca264c0"
  file: "./target/debug/test"
  skip_cleanup: true
  on:
    tags: true