[package]
name = "test"
version = "0.1.0"
authors = ["Антон Синицын <antony@email.su>"]
edition = "2018"
build = "build.rs"

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket" }
rocket_codegen = { git = "https://github.com/SergioBenitez/Rocket" }
multipart = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"

[dependencies.rocket_contrib]
default-features = false
features = ["handlebars_templates", "json"]
git = "https://github.com/SergioBenitez/Rocket"