version: 2.1
jobs:
  fetch:
    docker:
      - image: rust:latest
    working_directory: /mnt/project
#    environment:
#      RUSTUP_HOME: "/root/.rustup"
#      CARGO_HOME: "/root/.cargo/bin"
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-v1-{{ checksum "Cargo.toml" }}-
            - cargo-v1-
      - run: apt-get update && apt-get install -y wget curl
      - run: whereis rustup
      - run:
          name: "Install Rustup"
          command: |
            set -eux; \
            PATH="${PATH}:$HOME/.cargo/bin" \
            RUSTUP_HOME="$HOME/.rustup/" \
            CARGO_HOME="$HOME/.cargo/" \
            url="https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init"; \
            /usr/bin/wget "$url"; \
            chmod +x rustup-init; \
            RUSTUP_USE_CURL=1 ./rustup-init -y --no-modify-path --default-toolchain nightly; \
            rm rustup-init; \
            chmod -R a+w+x $RUSTUP_HOME $CARGO_HOME; \
            $HOME/.cargo/env; \
            rustup --version; \
            cargo --version; \
            rustc --version; \
            cargo update; \
            cargo fetch;
      - persist_to_workspace:
          root: "."
          paths:
            - Cargo.lock
      - save_cache:
          key: cargo-v1-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
          paths:
            - /usr/local/cargo/registry
            - /usr/local/cargo/git
  test:
    docker:
      - image: rust:latest
    working_directory: /mnt/project
    steps:
      - checkout
      - attach_workspace:
          at: "."
      - restore_cache:
          keys:
            - cargo-v1-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
      - run: rustup default nightly
      - run: apt-get update
      - run: apt-get install -y libvips*
      - run:
          name: Print version information
          command: rustc --version; cargo --version
      - run:
          name: Build and test with nightly Rust
          command: cargo test --verbose --frozen
  build:
    docker:
      - image: rust:latest
    working_directory: /mnt/project
    steps:
      - checkout
      - attach_workspace:
          at: "."
      - restore_cache:
          keys:
            - cargo-v1-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
      - run: rustup default nightly
      - run: apt-get update
      - run: apt-get install -y libvips*
      - run:
          name: Print version information
          command: rustc --version; cargo --version
      - run:
          name: Build and test with nightly Rust
          command: cargo build --verbose
#      - image: rust:latest
#  publish:
#      - image: rust:latest
  deploy:
    docker:
      - image: docker:latest
    working_directory: /mnt/project
    steps:
      - checkout
      - attach_workspace:
          at: "."
      - restore_cache:
          keys:
            - cargo-v1-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}

      - run: apt-get update && apt-get -y install apt-transport-https ca-certificates curl gnupg-agent software-properties-common sudo
      
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
            
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose

#      
#      - run: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
#      - run: apt-key fingerprint 0EBFCD88
#      - run: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
#      - run: apt-get update
#      - run: apt-get -y install docker-ce docker-ce-cli containerd.io
#      - run: curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
#      - run: chmod +x /usr/local/bin/docker-compose
#      - run: sudo service docker start
#      - run: sudo docker run --privileged hello-world
      - run: docker-compose up -d
workflows:
  version: 2.1
  continuous_deployment:
    jobs:
      - fetch
      - test:
          requires:
            - fetch
      - build:
          requires:
            - fetch
      - deploy:
          requires:
            - test
            - build
#      - publish:
#          requires:
#            - publish
