version: 2.1
jobs:
  fetch:
    docker:
      - image: rust:latest
    working_directory: /mnt/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-v1-{{ checksum "Cargo.toml" }}-
            - cargo-v1-
      - run: apt-get update && apt-get install -y wget curl
      - run: whereis rustup
      - run:
          name: "Install Rustup"
          command: |
            set -eux; \
            PATH="${PATH}:$HOME/.cargo/bin" \
            RUSTUP_HOME="$HOME/.rustup/" \
            CARGO_HOME="$HOME/.cargo/" \
            url="https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init"; \
            /usr/bin/wget "$url"; \
            chmod +x rustup-init; \
            RUSTUP_USE_CURL=1 ./rustup-init -y --no-modify-path --default-toolchain nightly; \
            rm rustup-init; \
            chmod -R a+w+x $RUSTUP_HOME $CARGO_HOME; \
            $HOME/.cargo/env; \
            rustup --version; \
            cargo --version; \
            rustc --version; \
            cargo update; \
            cargo fetch;
      - persist_to_workspace:
          root: "."
          paths:
            - Cargo.lock
      - save_cache:
          key: cargo-v1-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
          paths:
            - /usr/local/cargo/registry
            - /usr/local/cargo/git
  test:
    docker:
      - image: rust:latest
    working_directory: /mnt/project
    steps:
      - checkout
      - attach_workspace:
          at: "."
      - restore_cache:
          keys:
            - cargo-v1-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
      - run: rustup default nightly
      - run: apt-get update
      - run: apt-get install -y libvips*
      - run:
          name: Print version information
          command: rustc --version; cargo --version
      - run:
          name: Build and test with nightly Rust
          command: cargo test --verbose
  build:
    docker:
      - image: rust:latest
    working_directory: /mnt/project
    steps:
      - checkout
      - attach_workspace:
          at: "."
      - restore_cache:
          keys:
            - cargo-v1-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
      - run: rustup default nightly
      - run: apt-get update
      - run: apt-get install -y libvips*
      - run:
          name: Print version information
          command: rustc --version; cargo --version
      - run:
          name: Build and test with nightly Rust
          command: cargo build --verbose
  deploy:
    docker:
      - image: rust:latest
    working_directory: /mnt/project
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
      - attach_workspace:
          at: "."
      - restore_cache:
          keys:
            - cargo-v1-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
      - run: apt-get update && apt-get -y install apt-transport-https ca-certificates curl gnupg-agent software-properties-common sudo  python3 git

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
            
      - run: 
          name: Start container and verify it is working
          command: |
            set -x
            docker-compose -H $DOCKER_HOST -f docker-compose.yml build --no-cache --compress
  publish:
    docker:
      - image: rust:latest
    working_directory: /mnt/project
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publish to dockerhub
          command: |
            docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker tag dockerapp_dockerapp $DOCKER_HUB_USER_ID/dockerapp:$CIRCLE_SHA1
            docker tag dockerapp_dockerapp $DOCKER_HUB_USER_ID/dockerapp:latest
            docker push $DOCKER_HUB_USER_ID/dockerapp:$CIRCLE_SHA1
            docker push $DOCKER_HUB_USER_ID/dockerapp:latest
workflows:
  version: 2.1
  continuous_deployment:
    jobs:
      - fetch
      - test:
          requires:
            - fetch
      - build:
          requires:
            - fetch
      - deploy:
          requires:
            - test
            - build
      - publish:
          requires:
            - publish
