version: 2.1
jobs:
  fetch:
    docker:
      - image: rust:latest
    working_directory: /mnt/crate
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-v1-{{ checksum "Cargo.toml" }}-
            - cargo-v1-
      - run: cargo update
      - run: cargo fetch
      - run: apt-get update
      - run: apt-get install -y libvips*
      - persist_to_workspace:
          root: "."
          paths:
            - Cargo.lock
      - save_cache:
          key: cargo-v1-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
          paths:
            - /usr/local/cargo/registry
            - /usr/local/cargo/git
#  test:
#    docker:
#      - image: rustlang/rust:nightly
#    working_directory: /mnt/crate
#    steps:
#      - checkout
#      - attach_workspace:
#          at: "."
#      - restore_cache:
#          keys:
#            - cargo-v1-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
#      - run: rustup default nightly
#      - run:
#          name: Print version information
#          command: rustc --version; cargo --version
#      - run:
#          name: Build and test with nightly Rust
#          command: cargo test --verbose --frozen
#  build:
#      - image: rust:latest
#  publish:
#      - image: rust:latest
#  deploy:
#    docker:
#      - image: ragnaroek/kcov:v33
#        entrypoint: /bin/bash
#    working_directory: /mnt/crate
#    steps:
#      - checkout
#      - attach_workspace:
#          at: "."
#      - run: docker-compose up
workflows:
  version: 2.1
  continuous_deployment:
    jobs:
      - fetch
#      - test:
#          requires:
#            - fetch
#      - build:
#          requires:
#            - fetch
#      - publish:
#          requires:
#            - test
#            - build
#      - deploy:
#          requires:
#            - publish
